import {efficientFodderRecipe,formatPoints,opusSkillCosts,skillPointValues,ssrSl1Equivalent,standardSkillCosts} from "@/data/reference/skill-leveling";

function SkillCostTable({title,subtitle,costs}:{title:string;subtitle:string;costs:readonly number[]}){
  return <article className="skill-table"><header><span className="section-kicker">{subtitle}</span><h2>{title}</h2></header><div className="table-scroll"><table><thead><tr><th>Upgrade</th><th>Points</th><th>SSR SL1</th><th>Optimized direct feed</th></tr></thead><tbody>{costs.map((cost,index)=><tr key={index}><td>SL{index+1} → {index+2}</td><td>{formatPoints(cost)}</td><td>{ssrSl1Equivalent(cost)} equivalent</td><td>{efficientFodderRecipe(cost)}</td></tr>)}</tbody></table></div></article>;
}

export function SkillLevelPage(){return <div className="page-stack reference-page">
  <header className="page-header"><div><p className="breadcrumb"><span>Reference</span></p><h1>Weapon skill leveling</h1><p className="page-intro">Two cost curves, SSR-only direct-feed recipes, and a clear place for Academy M1 overflow.</p></div><dl className="stage-summary"><dt>Coverage</dt><dd>SL1 → SL25</dd></dl></header>
  <div className="skill-value-strip">{skillPointValues.map((item)=><div key={item.label}><span>{item.label}</span><strong>{formatPoints(item.points)} pts</strong></div>)}</div>
  <section className="skill-tables"><SkillCostTable title="Standard SSR" subtitle="Normal · Magna · EX" costs={standardSkillCosts}/><SkillCostTable title="Dark Opus / high-tier" subtitle="Opus · Ultima · Bahamut · Seraphic · Draconic" costs={opusSkillCosts}/></section>
  <section className="skill-advice"><article><div><span className="section-kicker">SSR-only direct feed</span><h2>Separate this from the Anvil.</h2></div><div><p><strong>The table is the lazy manual route:</strong> each recipe uses only SSR weapons. Raising fodder to SL2–4 does not reduce the total SSR copies consumed; it compresses the final feed into fewer slots.</p><p><strong>The Anvil’s SL1 → 10 convenience applies to both cost curves,</strong> but it cannot run on SSR reserve points alone. It pre-levels SSR fodder using reserved R/SR points. Auto-reserve farmable R/SR weapons and keep reducing Premium Draw SR weapons for stones.</p><p>Reserve surplus farmable SSRs only after securing every grid, uncap, awakening, and specialty copy. Reduce later overflow when weapon stones or elemental materials are the actual bottleneck. Never auto-reserve Premium Draw SSR weapons.</p></div></article>
  <article><div><span className="section-kicker">Academy M1 verdict</span><h2>Keep first. Feed directly later.</h2></div><div><p>An Academy M1 weapon at SL10 carries <strong>10,000 points</strong>. It exactly pays an Opus SL10 → 11 step. For Opus SL15 → 16, two SL10 M1 weapons cover 20,000 of 25,000 points; add SSR SL4 + SSR SL1.</p><p><strong>Never recycle an already-leveled weapon into the Craftsman’s Anvil.</strong> Recycling records one SSR unit regardless of skill level, destroying the SL10 multiplier. Feed it directly once it has genuinely left every grid.</p><p>A 3★ Academy weapon instead reduces as four copies. Choose reduction when stones or elemental materials block M3; otherwise its 10,000 direct skill points are especially useful for Opus SL10–20.</p></div></article></section>
  <p className="source-note">Ordinary weapons generally cap at SL10 at 0–3★, SL15 at 4★, and SL20 at 5★. Dark Opus reaches SL25 after 6★ transcendence Stage 5. Recipes favor the fewest final feed slots and show unavoidable overpayment below exact 1,000-point increments.</p>
 </div>}
